[project]
name = 'Tokenized-Robotics-Swarm-Intelligence-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.manufacturer-verification]
path = 'contracts/manufacturer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-optimization]
path = 'contracts/performance-optimization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
